### ISSUE TITLE
Command Line x Bsnes Plus

### ISSUE THREAD

**Issue by AlanRibas** [devinacker/bsnes-plus#115]
I'm using the Bsnes Plus emulator to emulate the "SUFAMI TURBO" system.
I'm trying to make it work along with a frontend called GameEx. Could someone tell me where to find the command lines of this emulator?
And what command lines are needed to start a SUFAMI TURBO game?

**Comment by Optiroc** [comment]
Here are the options in their entirety: [arguments.cpp](https://github.com/devinacker/bsnes-plus/blob/master/bsnes/ui-qt/application/arguments.cpp)

Loading Sufami Turbo and Super Gameboy roms from the command line is not possible without additions, I believe.

**Comment by AlanRibas** [comment]
Thank you for replying to me, but I do not have the slightest idea of what to do with this information you gave me.

**Comment by Optiroc** [comment]
I was on the phone when writing my first reply, so maybe I was a bit brief. Here are the current command line options:

```
Usage: bsnes+ [options] filename

  -h / --help                       show help
  --show-debugger                   open debugger window on startup
  -b / --breakpoint <breakpoint>    add breakpoint

  Breakpoint format: <addr>[-<addr end>][:<rwx>[:<source>]]
                     rwx = read / write / execute flags
                     source = cpu, smp, vram, oam, cgram, sa1, sfx
```
The `filename` argument is analogous to the `Load Cartridge...` menu option. For launching roms for which you need to use the `Load Special` dialogs, someone needs to add that logic to `arguments.cpp`. (

**Comment by devinacker** [comment]
I suppose I can do something like the following:

```
-st        load Sufami Turbo cartridge
-sgb       load Super Game Boy cartridge
-bsx       load BS-X cartridge
-bsxslot   load BS-X slotted cartridge
```

And then `filename` would just be the base cartridge name followed by the slot cartridge name(s), i.e.

`bsnes -st sufamiturbo.sfc slotA.sfc slotB.sfc`

Would that be sufficient?

**Comment by AlanRibas** [comment]
Many thanks for the info devinacker !!
I've passed this information on to the person in the Gameex forum. In summary, apparently the emulator can not start a SUFAMI TURBO game using only the command line.
Someone gave me the option to use the retroarch to emulate this sietam along with the gameex frontende. I think I'll try.

Thank you very much to all who posted to help me !!! Thanks guys!

**Comment by Optiroc** [comment]
@devinacker That would be a neat addition. 🔝

**Comment by devinacker** [comment]
Related: I finally got around to checking out libSFX and noticed that it had a break-on-WDM macro, nice to see that it's been useful :)

**Comment by Optiroc** [comment]
@devinacker Absolutely! Works great, too bad the SPC700 doesn't have an instruction as perfect to hijack for the same purpose. Maybe `sleep` could work though? Since there's no interrupt sources connected it can't be put to any reasonable use, can it..?

Also related: I've been wanting to add parsing of ca65 symbol files to the bsnes+ debugger for a while, with some provision for certain labels to act as breakpoints (matching a certain string pattern for x/r/w breakpoints probably). I think I've seen some notes that you've been wanting to rewrite the disassembly view so I've been kind of putting it off, though (since, to make good use of the symbols I'd probably want to make some big changes to the disassembly view, too).

**Comment by devinacker** [comment]
I'd rather not use `sleep` as a breakpoint because it isn't normally a no-op, unlike `wdm`. 

Alternate idea: using a dummy branch, either `bra #$00` or a short nonzero `bra` with a small signature afterward (like `55 aa` or something). That'd still be easy for the debugger to detect without actually having any serious impact on execution otherwise.

Re: disassembly, I'm still not totally sure how I want to re-implement the actual disassembly window, but it wouldn't be that hard to modify single-instruction disassembly to support looking up symbol names.

**Comment by Optiroc** [comment]
Yeah, true, regarding `sleep` (or `stop`); it's tempting since the instruction is useless in practice – but it's function is emulated properly (I assume) so to hijack its behaviour one would also need to make it a nop. So yeah, that would be messy. `bra #$00` is much better.

As a stop-gap solution for making breakpoints in source I also made a little [script](https://github.com/Optiroc/libSFX/blob/master/tools/make_breakpoints) that extracts `-b` arguments from a ca65 symbol file, which can be seen put to [use](https://github.com/Optiroc/libSFX/blob/master/examples/SMP-Test/Makefile#L6) [here](https://github.com/Optiroc/libSFX/blob/master/examples/SMP-Test/SMP-Play/Play.s700#L39).

Maybe it's also time to make the snes::debugger::breakpoint[] array an std::list (or appropriate data structure from nall, I guess everything beneath snes:: is STL free)?

**Comment by devinacker** [comment]
Getting rid of the fixed number of breakpoints has been a TODO item for a while. After that I wanted to have a persistent list of breakpoints that gets saved/loaded automatically like FCEUX, which should be simple now that there's a text-based breakpoint format for arguments now.

**Comment by devinacker** [comment]
In case this is useful at all, as of e4c125b1c831cb07eaddf88ef68412619a2b10f3 you can now enable a debugger option to store breakpoints in a file between sessions. If you want to generate one yourself, they have the extension `.bp` (otherwise same name as the ROM) and contain one breakpoint per line, using the same syntax as the command line argument.

(I said I was going to do that _after_ removing the breakpoint limit but I haven't done that yet, so I guess I'm doing things a bit backwards)

I also haven't actually added the command line options that this issue was supposed to be about in the first place, but I'll do that soon enough.

**Comment by SigmaVirus** [comment]
@devinacker How are things going with this?

The ability to start Super Game Boy games through command-line is a very sought out feature which I'm really looking forward to use!
