### ISSUE TITLE
Feature request: "Breakpoint here" in memory viewer

### ISSUE THREAD

**Issue by mrehkopf** [devinacker/bsnes-plus#118]
This probably isn't a popular use case but here it is:
More often than not I am working with the memory viewer to trace code execution with help of the usage map. It would be super convenient to be able to click on a hex value in the memory viewer and set a breakpoint (maybe bring up a little dialog to select r/w/x but even a pull down menu that allows you to set either one of them would be very very useful).

**Comment by devinacker** [comment]
The only real reason I haven't already implemented this is because of the somewhat small maximum number of breakpoints that are currently supported. Now that defining breakpoints on the command line and/or in separate files is supported, I'm planning to remove the breakpoint limit which should make it much more comfortable to add/delete them from the memory viewer in the future.
