### ISSUE TITLE
Breakpoints for register ranges are inconsistent

### ISSUE THREAD

**Issue by danielburgess** [devinacker/bsnes-plus#119]
![2017-05-04](https://cloud.githubusercontent.com/assets/1649107/25692202/0794245a-305e-11e7-9453-0b6ed8587789.png)

Using v073+3a

The example is when debugging Megaman X, but I'm fairly sure it happens with other ROMs.

Please refer the screenshot. Reading the joypad registers in a range sometimes fires, other times not. However, if I set the breakpoint on $4218 with nothing in the second box, the breakpoint fires every time.

**Comment by devinacker** [comment]
Sorry for the late response, but #17 explains this one a bit. Basically it's kind of a lazy performance measure to make sure that breakpoint ranges don't slow down emulation too much.

I probably ought to come up with a solution for this one at some point, since it's even been kind of annoying for myself as well.
