### ISSUE TITLE
CX4 Chip & FastROM

### ISSUE THREAD

**Issue by justin3009** [devinacker/bsnes-plus#128]
There's a specific check for CX4 and LoROM but if you attempt to do FastROM with the CX4 chip, it disables it entirely.

**Comment by devinacker** [comment]
(I saw your RHDN thread about this earlier, but I wasn't logged in at work so I didn't reply)

You can enable FastROM without modifying the mapping bits in the header, as long as you still set $420D and use addresses above $800000. The SNES doesn't actually know or care what the contents of the cartridge header are (unless you count the interrupt vectors as being part of the header).

The specific check for $20 when detecting the Cx4 is just a heuristic that bsnes (and possibly other emulators) use to make sure it doesn't get falsely detected for ROMs that don't actually use it. I could modify said check to support $30 as well, but trying that might make it inconsistent with other emulators. It's probably better to just play it safe and keep the values the same as the original games.

**Comment by Optiroc** [comment]
In parallell I talked to justin on discord and I kinda took a liking to the idea of having the header showing that it's a speed improved version of a Cx4 game. But now after a good nights sleep I realize it wasn't a good idea to enable Cx4 with other header makeups, since pretty much all emulators (and SD2SNES) use the same heuristics...

On a related note, making speed improvement hacks is something I've thought about a bit lately and I have some ideas for a "performance analyzis" view in bsnes+.
