### ISSUE TITLE
Export Video RAM/Tilemap Viewer to image

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#143]
It would be nice to have a screenshot feature for the Video RAM or Tilemap Viewers in order to extract individual sprites or layers from the game.  It would also be nice to have an option to override color 0 in each palette.  That would make it a lot easier to remove the background from layers, either by changing it to a unique color that can be easily removed, or else just replacing it with alpha in the exported screenshot.

**Comment by undisbeliever** [comment]
I'll work on this weekend and should have it done late tomorrow.

This is going to require a bit of refactoring of the tile renderer code, but I have an idea of how to tackle it.

**Comment by undisbeliever** [comment]
Implemented export to png image and override background color functionality to the TilemapViewer and the TileViewer. 

Push Request: https://github.com/devinacker/bsnes-plus/pull/145

P.S. Sorry about the lateness, was unable to push this yesterday due to a power cut.

P.P.S. Could you please test out the new Tile Viewer and let me know what you think.

**Comment by qwertymodo** [comment]
The new tile viewer is great!  No worries about the timeframe, we're all volunteers, after all ;)

**Comment by devinacker** [comment]
Gonna go ahead and close this since it's covered by the aforementioned PR (which is probably finally on its way to being merged now).
