### ISSUE TITLE
Transition to Qt5

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#146]
It would be nice to update the toolchain a bit.  It opens the door to enabling the use of some of the newer tools, and also simplifies the build environment setup, since newer MinGW builds of Qt include the MinGW files in the installer, so you don't have to meticulously check that your MinGW version matches the version that Qt was built against.  A quick test build seems to indicate that everything builds just fine on Qt5 (tested with 5.4.2).  If it really is drop-in compatible, then all that really needs to happen is to update the documentation.

Steps to build:

Download the latest MinGW build of Qt.  The latest I can find is 5.4.2, here: http://download.qt.io/archive/qt/5.4/5.4.2/qt-opensource-windows-x86-mingw491_opengl-5.4.2.exe

At the Select Components screen, expand the Tools list and select MingGW 4.9.1 to install the full MinGW toolchain.

Add the new PATH variables, or update your existing PATH.

Alternatively, instead of modifying PATH directly, I just added the following lines to the top of bsnes/cc.bat:

SET PATH=C:\Qt\5.4.2\Tools\mingw491_32\bin;%PATH%
SET QTDIR=C:\Qt\5.4.2\5.4\mingw491_32

Run clean, or manually clear the obj and out directories, then run cc.bat

Copy Qt5Core.dll and Qt5Gui.dll from the Qt installation directory and the libgcc/libgomp/libstdc++/libwinpthread .dll's from the MinGW directory inside the Qt directory

**Comment by devinacker** [comment]
I'm probably going to do this after the next release is finally out (which should be somewhat soon).

I'm pretty sure the online/unified installers for Qt up through 5.9.2 still have MinGW builds as an option. However, I think all the official Windows builds of Qt 5 are 32-bit except for the most recent VS2017 ones, and the project I had been using for prebuilt 64-bit Qt binaries stopped at 5.5.0. I'll have to figure something out about that since I want to make 64-bit builds the standard from now on.

**Comment by devinacker** [comment]
just closing this since the discussion was basically continued in the related PR
