### ISSUE TITLE
Can't compile bsnes for Void MUSL

### ISSUE THREAD

**Issue by kenny-w7** [devinacker/bsnes-plus#167]
Hello! I was hoping you might be able to help me figure out what dependencies I am missing! 
I use your bsnes-plus on my arch linux computers, but install it via the AUR.

https://pastebin.com/KTCu7y3r

**Comment by Optiroc** [comment]
Looks like there’s moc-generated headers in your tree that are generated with another version on Qt than the included headers. Try `make clean` and then do a single threaded make (so any errors will be easier to parse).

**Comment by undisbeliever** [comment]
You need to tell the makefile the location of the Qt4 libraries and build utils.

Try:

    export qtpath=/usr/lib/qt4
    make clean
    make

**Comment by devinacker** [comment]
undisbeliever is likely correct, The default is to use whichever versions of the Qt build tools are located in your `PATH` unless you specify otherwise, which may be problematic if you have both Qt 4 and 5 installed.

Migration to Qt 5 is going to (finally) happen after the upcoming v4 release so this should be less of a problem.

**Comment by kenny-w7** [comment]
thanks guys, sorry I've been busy lately.
