### ISSUE TITLE
Address mirroring not working properly for Breakpoint ranges

### ISSUE THREAD

**Issue by Arnethegreat** [devinacker/bsnes-plus#17]
Breaking on 7E0100 as a single address breaks normally on a read like LDA $0100.

But when adding a range 7E0100 - 7E0100 only breaks when game reads address directly. Only way to get it to break is to specify what bank it will read from.

**Comment by devinacker** [comment]
This was something I was a little worried about when actually implementing breakpoint ranges, because it's possible to specify a range that includes multiple address sources at once (like 000000 - 00FFFF, which includes ROM, WRAM, MMI/O, and potentially more). Thus support for mirroring becomes an issue because it's not really practical to check the source of every single page of memory in the range every time breakpoints are checked.
