### ISSUE TITLE
Make Paths textboxes editable

### ISSUE THREAD

**Issue by vince94** [devinacker/bsnes-plus#225]
I'm trying to copy and paste the same path into multiple textboxes in the Paths tab (to get rid of the .sym files mostly), but editing has been disabled. Could this be changed in a future version? If the purpose of this is data sanitation/validation, I'm sure a less annoying technique could be used...

An alternate solution to this issue would be to have three radio buttons like so:
- Store misc. files alongside loaded game
- Store misc. files alongside bsnes
- Custom

**Comment by devinacker** [comment]
This is pretty much just old bsnes behavior that I've wanted to change for a while now but still haven't... might as well do that soon since I had recently made some other tweaks to that tab anyway. I'll probably just go ahead and make the existing fields editable without messing with the actual layout.
