### ISSUE TITLE
update document

### ISSUE THREAD

**Issue by jjfmz42015** [devinacker/bsnes-plus#236]
Update documentation located @ http://bsnes.revenant1.net/documentation.html to include that accuracy profile even though present doesn't allow the use of filters.

**Comment by jjfmz42015** [comment]
Also maybe document what firmware is required.

These two additions to the doc would help new users of bsnes plus a lot.

**Comment by devinacker** [comment]
The accuracy profile does support filters; the real problem is that most of the filters (except for NTSC) don't support input resolutions higher than 256x240, and the accuracy core always renders at a width of 512 pixels.

Removing that restriction would be easy enough, but then you'd just be scaling up to 1024x480 and then possibly having to scale it back down to fit the window, which kind of defeats the purpose of the upscaling filters. I guess it could still be reasonable for larger window or fullscreen sizes though.

As for firmware filenames, I'll probably include those somewhere as well.

**Comment by jjfmz42015** [comment]
The NTSC filter even though appears to work doesn't work correctly. If you try the NTSC filter in comp or performance mode look how less jaggy things look than in accurate. I know it's how the accurate ppu renders that causes them to not work. I just figured add it to the documents for new users to know right off the bat and add which firmwares to help them as well. This emulator I believe is going to see a rise in users.

I've been emulating since 1997. I currently have been playing with this, the new bsnes, mesen-s and snes9x and find this build to be pretty stable pretty compatible.

Mind you I'm in love with all the emulators I just listed I find every build has its strengths.

**Comment by devinacker** [comment]
Yeah, the increased internal resolution just causes filters to have less of an effect on the horizontal axis (the same would be true in non-accuracy builds for games that use high resolution screen modes)

Anyway, just for curiosity's sake I made an experimental branch that adds proper hi-res support to the other filter options: https://ci.appveyor.com/project/devinacker/bsnes-plus/build/artifacts

All of them have the same "issue" where accuracy builds will necessarily have less horizontal filtering because of the increased source resolution, but maybe it's worth supporting anyway.

Either way, I'll probably make a note of the difference in the documentation somewhere, along with general descriptions of what the different filters actually do, I guess.

**Comment by jjfmz42015** [comment]
will most def test this. DIdnt think it was possible to do.

Ill report back thanks.

**Comment by jjfmz42015** [comment]
At work right now but was curios so I already took the hi res build for a spin. Works nice from the looks of it. Have it running on my second monitor with ASP in accuracy and the filters are definitely doing their thing.

Wow thanks!!
