### ISSUE TITLE
Hang when using STP or infinite WAI

### ISSUE THREAD

**Issue by randomdude999** [devinacker/bsnes-plus#240]
When executing a WAI instruction with interrupts disabled, or when executing STP anywhere, the entire UI hangs.

**Comment by devinacker** [comment]
I can't test this at the moment since I'm away from home, but this seems like it might be related to #233, which I was unable to reproduce (and I've definitely been able to use STP instructions on the CPU side without issues before, though not necessarily recently). 

Do you know if you're able to get similar results with the issue described in #233?

**Comment by randomdude999** [comment]
Yeah, the effects seem to be identical. So probably a single root cause.

**Comment by devinacker** [comment]
Interesting, this may mean I'll still have a tough time reproducing it on my end though.

Do you have a test ROM that's able to make it happen quickly after loading? Also, does it seem to matter whether or not any specific windows (esp. debug-related ones) are open when it occurs?

**Comment by devinacker** [comment]
Actually, another thing worth trying - does this also happen for you when using the snesmusic plugin to load a SPC file in the emulator?

Loading SPCs purposely makes the CPU execute a `STP` instruction after loading and starting the SPC file, so that the S-SMP is basically "flying solo", and I've never had any issues in that regard.

**Comment by devinacker** [comment]
Actually, I might have figured out what the issue is. 

Do you have rewind support enabled? I backported some stuff from the current bsnes upstream involving potential deadlocks when saving states, which might have caused this issue to occur automatically when rewinding was enabled. Grab the latest commit (or appveyor dev build) and see if it works any better now.

**Comment by randomdude999** [comment]
Yup, disabling rewind fixes it in the old version, and it doesn't happen at all in the latest commit.
