### ISSUE TITLE
cgram access problems

### ISSUE THREAD

**Issue by Redstone-Ghost** [devinacker/bsnes-plus#281]
i was messing about with asm when i noticed cgram can be accessed at anytime. its only supposed to be able to be accessed during vertical horizontal and forced blank.
i linked a rom showing this
tested on build
[cgram rom.zip](https://github.com/devinacker/bsnes-plus/files/6137885/cgram.rom.zip)

 05.76-master

**Comment by devinacker** [comment]
CGRAM can be accessed at any time. The only thing that happens when accessing it during active display is that you'll read/write whichever palette index is currently being accessed by the PPU instead of the one selected via $2121.

You can see exactly the same result when running your test ROM on a real SNES:

![image](https://user-images.githubusercontent.com/4616298/111088940-f52fa780-84ff-11eb-8865-49b626a38048.png)

**Comment by Redstone-Ghost** [comment]
sorry forgot to uncheck fast ppu when testing in bsnes
