### ISSUE TITLE
Disassembler view does not heed instruction boundary

### ISSUE THREAD

**Issue by mrehkopf** [devinacker/bsnes-plus#3]
It seems the disassembler view disassembles from every byte offset instead of skipping the bytes that belong to the same instruction. The debugger main view does it correctly.
e.g. expected result:
```
c31527 and #$8f
c31529 ora $68
c3152b sta $75
c3152d lda $69
c3152f asl a
c31530 asl a
```

actual result:
```
c31527 and #$8f
c31528 sta $856805
c31529 ora $68
c3152a pla
c3152b sta $75
c3152c adc $a5,x
c3152d lda $69
c3152e adc #$0a
c3152f asl a
c31530 asl a
```

**Comment by devinacker** [comment]
Yeah, this is a known issue. The reason is that currently every single byte in an instruction is marked with the 'executed' flag for consistent highlighting in the memory view, and the disassembler uses that flag to figure out where the start of known instructions are, so as a result it ends up disassembling every byte. I have a quick fix planned but haven't got to it yet.

**Comment by devinacker** [comment]
fixed in b8bc79551d22732715d85da7ff10271dbf827cf5

**Comment by mrehkopf** [comment]
Awesome, works great.
Thank you for making this! It is the most usable bsnes flavor I can think of.
Really looking forward to the register editor. :)

**Comment by devinacker** [comment]
Glad to hear :)
The register editor should be in soon, I was hoping to have added it last week to be able to do a proper release but other things got in the way...
