### ISSUE TITLE
Wrong cycle counts for 16-bit operations with implied addressing (and more)

### ISSUE THREAD

**Issue by furrykef** [devinacker/bsnes-plus#32]
I'm using the BSNES Plus 0.73+1 from the releases tab.

I believe a 16-bit INX instruction should execute in only 14 master clocks (the H clock in the debugger) in SlowROM and 12 on FastROM, but instead it takes 22 in SlowROM and 18 in FastROM. Presumably it's doubling the number of fetch clocks since it's a 16-bit operation, but it shouldn't, because it's not fetching any extra bytes from memory. This issue appears to apply also to INY, INC A, DEX, DEY, DEC A, ASL A, LSR A, TAX, TXA, TAY, TYA, TXY, TYX, TDC, TCD, TXS, TSX -- basically any 16-bit operation that uses implied or accumulator addressing.

This does not happen in BSNES 0.65.

**EDIT**: It's not just 16-bit operations. CLI is taking 22 (8+8+6) master clocks in SlowROM when it should be taking 14 (8+6). I'd edit the title of the bug, but I can't.

**Comment by devinacker** [comment]
cc @awjackson

**Comment by awjackson** [comment]
I'm afraid this one is your fault. In bsnes-plus *every* instruction is taking an extra memory cycle while stepping in the debugger. The culprit is the extra op_read() you added to `CPUDebugger::op_step()` to see if the instruction is a `jsr` or `ret`:

`uint8 opcode = CPU::op_read(opcode_pc);`

The simplest fix would be to change that op_read() to a disassembler_read(). And don't forget to make the same change to the SA-1 debugger as well, since it has exactly the same bug.

**Comment by devinacker** [comment]
Ouch. Yeah, that's my fault for not double-checking that back when disassembler_read() was added a few months back (and for somehow not being aware of op_read()'s timing effects way back when I first started extending the debugger...)

(Didn't mean to suggest it might have been your fault, by the way, I just wasn't actually able to look into it until just now, and thus didn't know if it was also an upstream issue or not. Thanks for checking it out regardless.)

Should be fixed by c800e901bfe39fb2a6f1394d42adb8f20527f902.
