### ISSUE TITLE
Symbol descriptions

### ISSUE THREAD

**Issue by jeffythedragonslayer** [devinacker/bsnes-plus#330]
![image](https://user-images.githubusercontent.com/13253146/175456127-b48334dc-9d22-4b84-9fc1-4a179e55195d.png)

**Comment by devinacker** [comment]
I have no idea what this issue is supposed to be asking or suggesting, but if it's about the "description" column being unused/non-editable, it's on the todo list.

Please actually _say something_ in issue reports instead of just pasting a completely nondescript screenshot or I'm just going to close it on sight next time.

**Comment by jeffythedragonslayer** [comment]
Ok, sorry.  I have not seen a todo list.
