### ISSUE TITLE
Error compiling with PROFILE_PERFORMANCE

### ISSUE THREAD

**Issue by lab313ru** [devinacker/bsnes-plus#39]
Subj.
Also there is `ALT_CPU_CPP` and `ALT_CPU_HPP` defines. I think, it should be `CPP` in every case.

**Comment by lab313ru** [comment]
It is still cannot be compiled. Recheck it, please!

**Comment by devinacker** [comment]
Can you please give me the actual error that occurs when you try to compile? Also, what compiler/toolchain are you using?

**Comment by lab313ru** [comment]
`'mmio_r2180': is not a member of 'SNES::CPUDebugger'`
`bsnes\snes\cpu\debugger\debugger.cpp line 129`

**Comment by devinacker** [comment]
https://github.com/devinacker/bsnes-plus/blob/master/bsnes/snes/Makefile#L12-L36

Make sure the correct version of the CPU is being built for the profile you want (for performance that's `snes/alt/cpu` instead of `snes/cpu`, which is what the `#ifdef ALT_CPU_CPP` is for). 

Also make sure `PROFILE_PERFORMANCE` is defined for the entire project, otherwise the correct source files might not always be included.

**Comment by lab313ru** [comment]
Problem was in compiling `snes/cpu` instead of `snes/alt/cpu`. My fault.
