### ISSUE TITLE
S-PPU CGRAM write breakpoints don't trigger

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#74]
I can't get any CGRAM write breakpoints to trigger, on any address.  Not sure if it makes any difference, but they may all be DMA transfers, I haven't tried manually writing to $2122.

**Comment by qwertymodo** [comment]
I guess the coffee is finally kicking in... are write breakpoints even supported for DMA transfers?  I guess if they were, they would trigger on the write to $420b, or on the next instruction?  I'm not sure how (or even if) this is currently handled for other destination besides CGRAM.

**Comment by devinacker** [comment]
If I remember right, currently the break will occur on the instruction _after_ the DMA is initiated. 

I only just recently implemented CGRAM breakpoints for non-compatibility builds, but if DMA doesn't work with those at all then it might be due to a profile-specific implementation detail or something.

**Comment by devinacker** [comment]
CGRAM/VRAM/OAM breakpoints (for both manual writes and DMA) seem to work fine with the accuracy and compatibility profiles.

I just updated the debugger slightly to actually display the current instruction when PPU breakpoints occur, same as with normal CPU/coprocessor breakpoints. DMA transfers will still end up showing the instruction after the transfer, but you can use the disassembler view to see the instruction that triggered the DMA as well.
